name: Build

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Build
        run: |
          sudo chmod -R 777 *
          ./aarch64-linux-android-as opus/celt/arm/armopts.s -o opus/celt/arm/armopts.o
          ./Build.sh
          
      - uses: actions/upload-artifact@v2
        with:
          name: opus-arm64-v8a
          path: obj/local/arm64-v8a/libopus.a

      - uses: actions/upload-artifact@v2
        with:
          name: opus-armeabi-v7a
          path: obj/local/armeabi-v7a/libopus.a

      - uses: actions/upload-artifact@v2
        with:
          name: opus-x86
          path: obj/local/x86/libopus.a

      - uses: actions/upload-artifact@v2
        with:
          name: opus-x86_64
          path: obj/local/x86_64/libopus.a
