name: Build

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildArm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r15c-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./Build.sh armeabi-v7a
          
      - uses: actions/upload-artifact@v2
        with:
          name: opus-Arm
          path: opus/.libs/libopus.a

  buildArm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r15c-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./Build.sh arm64-v8a

      - uses: actions/upload-artifact@v2
        with:
          name: opus-Aarch64
          path: opus/.libs/libopus.a

  # This workflow contains a single job called "build"
  buildx86:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r15c-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./Build.sh x86
          
      - uses: actions/upload-artifact@v2
        with:
          name: opus-x86
          path: opus/.libs/libopus.a

  # This workflow contains a single job called "build"
  buildx86_64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r15c-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./Build.sh x86_64
          
      - uses: actions/upload-artifact@v2
        with:
          name: opus-x86_64
          path: opus/.libs/libopus.a
